# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6699bed8eb93b22175811655c045cf32e30010c42f84e3859b657c9dc00a70f7e538a5d6cc77a0b03e707d86679019d394a5cff6e5b18ea8053c53d2854907c2

test:
  secret_key_base: 7aabcab9bbb1d332bb4fed24475ecdd22ad1967ca4eddc1bcb6fa6d151a6cd28206735f1ef14aae64c481597367630d01befc192f643f0fc8b4efe63e4c5d239

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
